spring:
  application:
    name: jeroka-ia-docs-events-worker
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: jeroka-ia-docs-events-worker
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: ${PORT:3016}

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    fr.jeroka: INFO
